### ISSUE TITLE
Deploy to non-local cluster failed with "Entry Point approot\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe not found" error

### ISSUE THREAD

**Issue by zoalasaurusrawr** [c3-ls/ServiceFabric-Http#14]
Hello,

When deploying to a non-local cluster, all builds succeed and the deploy begins, but fails with the error:

_The EntryPoint approot\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe is not found._

**I have tried the following:**

-dnvm use 1.0.0-rc1-update1
-dnvm use 1.0.0-rc1-update1 -a x64 (As the gateway and service projects target x64)
-Copied the .dnx/runtimes folder into what I perceive to be the "approot" (ServiceFabric- HttpServiceGateway-0.3.0 folder)

**Comment by cwe1ss** [comment]
Hi! You have to change the EntryPoint/ExeHost/Program path in the ServiceManifest.xml - replace x86 with x64.
If visual studio keeps changing it back to x86 on build or publish, you can disable automatic updates by opening the xproj file with a text editor and setting `UpdateServiceFabricManifestEnabled` to `false`.

Also make sure that `dnvm list` has the x64 entry selected as the "default" alias - this is the one, visual studio uses.

Hope that helps!

**Comment by zoalasaurusrawr** [comment]
This worked perfectly! thank you for your assistance. In trade, is there any assistance you need on the project to help port it to RC2? Or any other tasks I can jump in and help with?
