### ISSUE TITLE
Implement Circuit Breaker Pattern

### ISSUE THREAD

**Issue by cwe1ss** [c3-ls/ServiceFabric-Http#21]
The current retry logic is dangerous because it could prevent unhealthy services from recovering gracefully. 

Ideally, we would use Polly.Net for this. However this might be hard to integrate into the existing IExceptionHandler because the retry logic is spread over several components in the Service Fabric SDK.

**Comment by nareshkhatri81** [comment]
Hi Team,
is there any update on when this would be part of Service Fabric SDK ?
Thanks,
Naresh

**Comment by cwe1ss** [comment]
@nareshkhatri81 this is a 3rd party project and not affiliated with the official Service Fabric SDK. However, Service Fabric contains a different, official proxy implementation: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reverseproxy

I currently don't have any concrete plans on when/if a circuit breaker will be implemented into this library. We are currently researching more professional "service mesh"-solutions like [linkerd](https://linkerd.io/) and [istio](https://istio.io/). These provide circuit breaker functionality and lots of other features. So I'm not yet sure how this will affect features of this library.

**Comment by cwe1ss** [comment]
We've recently switched to Service Fabric's built-in HTTP reverse proxy so we're no longer using this ourselves. I'll therefore close all open issues, update the description and mark this project as "Archived".
