### ISSUE TITLE
Configure retry behavior based on the HTTP method

### ISSUE THREAD

**Issue by cwe1ss** [c3-ls/ServiceFabric-Http#22]
It should be possible to decide based on the HTTP method of the current request, if a retry should be attempted. This way, the gateway could be configured to e.g. only attempt retries for GET requests.

However, there might be scenarios, where a retry should always be attempted:
- Connect failures
- HTTP 404 responses, which could mean that the service has been moved
- HTTP 500 errors if people are sure that the server didn't modify any state
- resolve errors from Service Fabric

**Comment by zoalasaurusrawr** [comment]
I wonder if would be worth looking into Polly as a way to implement the retry logic
