### ISSUE TITLE
Microsoft.Extensions.Configuration based config for the gateway

### ISSUE THREAD

**Issue by cwe1ss** [c3-ls/ServiceFabric-Http#24]
In cases where we don't need any special code-based settings per service, we could read the whole configuration from an external provider. By using `Microsoft.Extensions.Configuration` we could support scenarios, where the configuration comes from a file, from a database, ...

E.g., there could be a config file like this:

``` json
{
  "Gateway": {
    "Services": {
      "fabric:/MyApp/MyService1": {
        "PathMatch": "/service1",
        "ListenerName": "OwinEndpoint"
      },
      "fabric:/MyApp/MyService2": {
        "PathMatch": "/service2"
      }
    }
  }
```

**Comment by zoalasaurusrawr** [comment]
Would you keep a generic handler and allow a config based set of handlers?

I would imagine in code, something like this with the new asp.net core:

app.UseGenericFabricHandler

and for config based routes from specific sources

app.UseEntityFrameworkHandlerProvider()
app.UseRedisHandlerProvider()
app.UseJsonHandlerProvider().

Obviously, this is like a scratch pad, not well thought through yet.

**Comment by cwe1ss** [comment]
merged. a file-based config would now look like this:

``` json
{
  "GatewayServices": [
    {
      "PathMatch": "/some-service1",
      "ServiceName": "fabric:/MyApp/SomeService1"
    },
    {
      "PathMatch": "/some-service2",
      "ServiceName": "fabric:/MyApp/SomeService2",
      "ListenerName": "OwinListener"
    }
  ] 
}
```

Startup.cs - ConfigureServices: `app.RunHttpServiceGateways(Configuration.GetSection("GatewayServices"));`

of course, this information could also come from a database, ...

the downside of this is that it doesn't allow you to specify a `ServicePartitionKeyResolver` since this must be a delegate. However, I guess people will be happy to use the existing `RunHttpServiceGateway` in that case anyway.

I also updated the wiki-page: https://github.com/c3-ls/ServiceFabric-Http/wiki/HTTP-Gateway
