### ISSUE TITLE
Run ASP.NET 5 site without fabric, content not served and settings not found

### ISSUE THREAD

**Issue by HakanL** [c3-ls/ServiceFabric-Http#28]
I have a ASP.NET 5 project (using the full .NET Framework, but with the new xproj project type) which has both wwwroot files and Web Api controllers. When I start it without the fabric I get an error that it can't find the appsettings.json (it all works when part of the fabric) and if I skip that (only has settings for logging) then it can't find any files (like index.html that exists in wwwroot).
Are there any other settings I should do for this to work? I haven't done much troubleshooting, I can see the command window with the requests but it doesn't show the local paths so I'm not sure how best to determine what has to be configured. The startup code is essentially the same as your sample HttpService (where I get the json FileNotFound error too), but with a wwwroot as well.

**Comment by cwe1ss** [comment]
Hi, did you start it with `dotnet run`? If yes, dotnet run builds your project and creates the DLLs in a subfolder - depending on your project.json it might or might not copy the static files to that directory as well. 

There are multiple things in ASP.NET Core that define how files are resolved. If you don't copy your files to the output on build (`buildOptions.copyToOutput` in project.json) than you have to specify the content root in your WebHostBuilder with `.UseContentRoot(Directory.GetCurrentDirectory())` ([see templates](https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Program.cs#L16)) and when you create your ConfigurationBuilder with `.SetBasePath(env.ContentRootPath)` ([see template](https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L18))

the build script in this project uses `dotnet publish` to create the package for Service Fabric. As you can [see here](https://github.com/c3-ls/ServiceFabric-Http/blob/master/samples/HttpService/project.json#L9), I've configured the project.json to include the appsettings.json file for that process.

Hope that helps.

**Comment by HakanL** [comment]
No I started it from within Visual Studio (selecting HttpService as profile). Let's focus on the HttpService project first, does it work for you if you run/debug it from Visual Studio? As mentioned it can't find the appsettings.json when I try it. The file isn't copied to the `ServiceFabric-Http\samples\HttpService\bin\Debug\net451\win7-x64` folder when starting debug from VS.

**Comment by HakanL** [comment]
Thanks for those template links, it helped, so now my project is working fine, but maybe it makes sense to update this sample to include those changes too?

**Comment by cwe1ss** [comment]
I updated the samples with #29 - thanks for pointing this out!

**Comment by HakanL** [comment]
Perfect, thanks!
