### ISSUE TITLE
Control path in RunHttpServiceGateway

### ISSUE THREAD

**Issue by HakanL** [c3-ls/ServiceFabric-Http#30]
I have this code in my gateway:
`app.RunHttpServiceGateway("/admin", "fabric:/MyFabric/AdminWebSite");`

So my admin web site runs under /admin. In my AdminWebSite I also have stuff like this:
`app.UseStaticFiles("/admin");`
so I can run the web site standalone without deploying to the cluster.

The issue is that these conflict, the path when running it in the cluster becomes http://localhost:5402/admin/admin/index.html but it should be http://localhost:5402/admin/index.html which it is if I run it standalone.

Is there a way I can control this in RunHttpServiceGateway so it doesn't add the /admin the URLs?

**Comment by cwe1ss** [comment]
In a typical web application, you don't need to use `app.UseStaticFiles("/admin")` - you can use just `app.UseStaticFiles()`. This automatically serves files from your `wwwroot` folder. Check [aspnet/templates](https://github.com/aspnet/Templates/tree/dev/src/BaseTemplates/StarterWeb) for the default Visual Studio project template.

this means your AdminWebSite would run on http://localhost:5402/index.html without the gateway, and on http://localhost:gateway-port/admin/index.html with the gateway.

**Comment by HakanL** [comment]
My issue is that it's a SPA and some of the JS files references files with absolute path (Aurelia), so I had to do the UseStaticFiles (and change some paths to actually say /admin). I think I figured out a way, I have to do some app.Use and manually check on the path and inject /admin when running as the fabric since it strips the /admin when forwarded to the web site.

**Comment by cwe1ss** [comment]
yes, this gateway does not automatically change URLs on HTTP responses, so if your application uses absolute URLs, it has to adjust its behavior based on whether it runs behind the gateway or not.

The gateway will [send a special HTTP-Header](https://github.com/c3-ls/ServiceFabric-Http/blob/master/src/C3.ServiceFabric.HttpServiceGateway/HttpRequestMessageExtensions.cs#L98) called `X-Forwarded-PathBase` that contains the part of the path under which the gateway is configured to serve the service. So in your case, it would contain "/admin". (might also be just "admin" - I'm not 100% sure)

**Comment by HakanL** [comment]
Ah, good, that may be a better way to check on that header. Thanks for your help!

**Comment by cwe1ss** [comment]
this middleware would be an easy solution if your application respects `Request.PathBase` when URLs are generated:

``` csharp
public class AdjustPathBaseMiddleware
{
    private readonly RequestDelegate _next;

    public AdjustPathBaseMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        string pathBase = GetPathBaseFromHeader(context);
        if (pathBase != null)
        {
            context.Request.PathBase = pathBase + context.Request.PathBase;
        }

        await _next(context);
    }

    private string GetPathBaseFromHeader(HttpContext context)
    {
        StringValues pathBaseObj;
        if (context.Request.Headers.TryGetValue("X-Forwarded-PathBase", out pathBaseObj))
        {
            string pathBase = pathBaseObj.ToString();

            // Security Checks
            if (!pathBase.StartsWith("/"))
                return null;

            // TODO: Further checks?

            return pathBase;
        }

        return null;
    }
}

// Use it as the first/one of the first middleware in Startup.Configure
// app.UseMiddleware<AdjustPathBaseMiddleware>();
```

**Comment by HakanL** [comment]
Thanks, but the issue is that this is a SPA site, most URLs are in static files so they don't use any base urls in the .NET world. But it's fine, I figured it out with a small middleware that just prefixes incoming requests so it works the same standalone vs under fabric.

**Comment by cwe1ss** [comment]
ok!
