### ISSUE TITLE
how to redirect Urls like the Azure Resource Manager

### ISSUE THREAD

**Issue by pksorensen** [c3-ls/ServiceFabric-Http#31]
Lets say your api that clients consume is similar to azure resource manager
/subscriptions/{guid}/resourcegroups/{randomstring}/providers/{set of providers}.

Lets say all providers are implemented as stateless services and based on the {set of providers} it now have to forward the request from the gateway. Is this also possible?

The examples given is all simple prefix examples /mypath.

How would one configure 50 different providers in a smart way with the Map ?

I am guessing one could easily do some regex/dictionaries lookup - i am curious if this is a bad idea in the map call? 

Cool project.

**Comment by cwe1ss** [comment]
Hi Poul,

we have overloads that use the [app.Map](https://docs.asp.net/en/latest/fundamentals/middleware.html#run-map-and-use)-feature of ASP.NET Core to distinguish different services by path. I'm not sure how flexible this feature is. If it allows you to specify a pattern or a predicate, you might be able to do a more complex selection. 

Whatever you do, the gateway middleware assumes that the selection-process correctly sets the `Request.PathBase` and `Request.Path` properties. The gateway uses whatever exists in `Request.Path` for its child call and it appends `Request.PathBase` as a custom HTTP header (X-Forwarded-PathBase).

This means, you might have to fiddle around with these properties if you don't want e.g. `/providers/{set of providers}` to be part of the child call.

It would definitely be easier if you could move the provider to the first part of the URL (e.g. `/providers/{providerName}/whatever-comes-here/{guid}/will-be-forwarded`). In this case, it would be a normal setup and you could use e.g the [configuration-based initialization](https://github.com/c3-ls/ServiceFabric-Http/wiki/HTTP-Gateway#iconfiguration-based-configuration-for-multiple-gateway-middleware-instances) to get all existing providers from a file/db/etc.

**Comment by cwe1ss** [comment]
please reopen if you have further questions.
