### ISSUE TITLE
dotnet install.ps1 script 404 error

### ISSUE THREAD

**Issue by isaacmcn** [c3-ls/ServiceFabric-Http#33]
Hi,

Just trying to build the code and am receiving a 404 error after "Installing dotnet SDK". Just wondering if 

`Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1"`

Should actually by

`Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1"`

Cheers,

Isaac

**Comment by cwe1ss** [comment]
seems like the name was changed. thanks for reporting it, this is now fixed!

**Comment by isaacmcn** [comment]
Excellent, thanks!
