### ISSUE TITLE
How to configure for SSL

### ISSUE THREAD

**Issue by BrentKrell** [c3-ls/ServiceFabric-Http#36]
Is there a way to configure the gateway to use SSL? There was a previous post on this, but that was before the project was upgraded. I haven't been able to successfully get SSL to work with a self signed certificate using the ASF 5.1.150. Sample code would be appreciated. This is what I've tried in the Gateway startup. I can http to work, but can't get the https to forward to the backend service.

```
        using (var builder = new ServiceFabricWebHostBuilder(args))
        {
            builder
                .UseUrls("http://localhost:5402", "https://localhost:5403")
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseKestrel(options =>
                {
                    // options.ThreadCount = 4;
                    options.NoDelay = true;
                    options.UseHttps(GetSslCertificate());
                    options.UseConnectionLogging();
                })
                .UseStartup<Startup>()
                //.UseServiceFabric()
                .Build()
                .Run();
       }
```

**Comment by cwe1ss** [comment]
Hi @BrentKrell ,
Do you want to expose your gateway to the internet? Unfortunately, that's not yet recommended by Microsoft. In that case, you should use WebListener instead of Kestrel - check out these recent posts by Microsoft:
- https://github.com/aspnet/Announcements/issues/204
- https://github.com/aspnet/KestrelHttpServer/issues/1108

If you just want to use SSL for your internal communication - Unfortunately, I haven't done that so far so I can't give you good guidance - just a few questions:
- Did you register the HTTPS endpoint in your ServiceManifest.xml?
- You write "can't get the https to forward to the backend service" - do you mean your gateway isn't accessible through HTTPS or your backend services? Your backend services would also need the HTTPS endpoints if you want to communicate with HTTPS between your gateway and your services

**Comment by cwe1ss** [comment]
Please also have a look at this previous issue https://github.com/c3-ls/ServiceFabric-Http/issues/26 which contains some guidance regarding ServiceManifest modifications etc.

**Comment by BrentKrell** [comment]
Hi @cwe1ss 
Yes, I want to expose my gateway to the internet. My scenario is I have some service fabric WebAPI micro services, some of which I want to expose to the internet as HTTPS endpoints via the Gateway. I see from the articles you linked that isn't recommended directly with Kestrel. I don't need HTTPS for internal communication between nodes. I will pursue the WebListener route then. My other option is to use the service fabric reverse proxy, which I don't like for some the reasons cited here [https://github.com/c3-ls/ServiceFabric-Http/issues/37](https://github.com/c3-ls/ServiceFabric-Http/issues/37)

Just for completeness, to answer your other questions. The backend WebAPIs I configured to use both HTTP and HTTPS and both were registered in ServiceManifest and I tried to setup the Gateway to forward requests to the backend WebAPIs. I could get this to work for HTTP requests to the gateway, but wasn't able to get HTTPS to work. From what I could tell it seemed like the requests were rejected at the gateway. I was able to call my WebAPIs directly with HTTPS bypassing the Gateway. I did try the code in issue #26 but I think that might be old or I couldn't find the right nuget packages to get that to compile with the latest ASF.

**Comment by markmonster** [comment]
For all the people who want to expose the API Gateway towards the outside world, two things should of course be considered.
1. Use HTTPS
2. Use WebListener

**1. Use HTTPS**
Of course setting up HTTPS makes sense, however you shouldn't consider this always to be easy. It's infrastructure stuff, that's not as easy as it sounds. However Ronald Wildenberg wrote a couple of interesting articles that will be of help.
- Running a local Azure Service Fabric cluster on SSL. http://ronaldwildenberg.com/running-an-azure-service-fabric-cluster-locally-on-ssl/
- Custom domain name and certificate for your Azure Service Fabric cluster. http://ronaldwildenberg.com/custom-domain-name-and-certificate-for-your-azure-service-fabric-cluster/

**2. Use WebListener**
If you take HttpGateway project from the Sample in this repository and modify the Startup.cs to sound like below, it will be running on both HTTPS and WebListener. However be sure to follow the steps in the articles mentioned above first.

``` csharp
public static void Main(string[] args)
{
    using (var builder = new ServiceFabricWebHostBuilder(args))
    {
        builder
                .UseUrls("https://+:443/")
                .UseWebListener()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseStartup<Startup>()
                .Build()
                .Run();
    }
}
```

**Comment by cwe1ss** [comment]
We've recently switched to Service Fabric's built-in HTTP reverse proxy so we're no longer using this ourselves. I'll therefore close all open issues, update the description and mark this project as "Archived".
