### ISSUE TITLE
ServicePointManager.DefaultConnectionLimit should have a sane value

### ISSUE THREAD

**Issue by rmja** [c3-ls/ServiceFabric-Http#44]
The default value of `ServicePointManager.DefaultConnectionLimit` is 2 which is an incredibly low value, especially for the gateway code. It practically limits the number of simultaneous requests to services running on the same host to 2.

If a replace `HttpCommunicationClientFactory`with a custom one, where I put
`ServicePointManager.DefaultConnectionLimit = 1024;` in the constructor, I get much more decent performance when forwarding requests to the same service.

**Comment by cwe1ss** [comment]
Hi, this is a global call so you could put it anywhere you want, right?! You could just call it on app startup and still use the existing class.

**Comment by cwe1ss** [comment]
I don't think it's a good idea to overwrite this value within a library as this affects the whole system. I do agree though that this value should be increased - thanks for pointing it out.

**Comment by rmja** [comment]
You are right. I was creating this issue in frustration over that such a global setting exists, and that it has severe implicitations. Maybe it should be pointed out in the readme instead?

**Comment by cwe1ss** [comment]
We've recently switched to Service Fabric's built-in HTTP reverse proxy so we're no longer using this ourselves. I'll therefore close all open issues, update the description and mark this project as "Archived".
