### ISSUE TITLE
OpenID Authentication fails

### ISSUE THREAD

**Issue by geedsen** [c3-ls/ServiceFabric-Http#45]
The Gateway, running on https, forwards to a Web service (ASP.NET Core 2.0) App service. This service Authenticates in the AzureAD , the login prompt is shown, the password given, the authentication is then returned to the service (via the gateway). But we get an error:
Correlation failed.

More specific: 

Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 POST http://localhost:31005/signin-oidc application/x-www-form-urlencoded 1849
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Warning: '.AspNetCore.Correlation.OpenIdConnect.nPsgswKM8iBEY69nNySdGvrTPu0qYnDfGKPdZa_iuug' cookie not found.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Information: Error from RemoteAuthentication: Correlation failed..
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 13134.8508ms 0 
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 POST http://localhost:31005/signin-oidc application/x-www-form-urlencoded 1849
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Warning: '.AspNetCore.Correlation.OpenIdConnect.nPsgswKM8iBEY69nNySdGvrTPu0qYnDfGKPdZa_iuug' cookie not found.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler: Information: Error from RemoteAuthentication: Correlation failed..
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 1673.1796ms 302 
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request starting HTTP/1.1 GET http://localhost:31005/Home/Error?message=Correlation%20failed. 

Is the cookie not being forwarded?

**Comment by geedsen** [comment]
Nobody?

**Comment by ltdavids** [comment]
Were you ever able to resolve this?

**Comment by geedsen** [comment]
No. we decided not to use the gateway because of it.

**Comment by cwe1ss** [comment]
Sorry for not replying, I’m on a sabbatical right now. It looks like your service did not correct proper absolute urls. As you can see in your output, it created localhost URL’s which are obviously not publically available.

**Comment by geedsen** [comment]
No the localhost is correct, this is on a local SF cluster on the development system.
