### ISSUE TITLE
Forward cookies from requests to service

### ISSUE THREAD

**Issue by arthur-rizzo** [c3-ls/ServiceFabric-Http#46]
Hi! 

I've been having problems when using the gateway because the cookies sent by the browser are not passed to the serviceFabric service. 

I don't know if this is a bug or not. perhaps sending the cookies could create security issues. I am not sure.

Is there a reason behind why the cookies are not copied from the original request?

Thanks. Your library has been very helpful!

**Comment by cwe1ss** [comment]
It should forward cookies without changing them. It would be great if you could try to debug this by storing the outgoing cookies (e.g. with fiddler) and the incoming cookies in your service (by enumerating Request.Cookies)

**Comment by arthur-rizzo** [comment]
I found what the problem was . The thing is, the cookies from the incoming request are copied into the outgoing request thrgouh headers but, in fact, they are not sent. For cookies to be passed in a request using headers, the HttpClientHandler needs to have property "UseCookies" set to false., otherwise they will be ignored. 

see this: https://stackoverflow.com/a/13287224/330334. It worked for me.

I think this should be some kind of parameter in the gateway options.

Thanks!!

**Comment by raol** [comment]
@cwe1ss I'm facing with exactly the same problem. 
Do you mind if I create pull request with an option to be passed to the `HttpClientHandler`, so `Cookie` header will be forwarded to a service?

**Comment by cwe1ss** [comment]
We've recently switched to Service Fabric's built-in HTTP reverse proxy so we're no longer using this ourselves. I'll therefore close all open issues, update the description and mark this project as "Archived".
